variable "aws_access_key" {
  type = "string"
}

variable "aws_secret_key" {
  type = "string"
}

variable "aws_region" {
  type = "string"
  description = "AWS region"
  default = "us-east-1"
}

variable "ami" {
  type="string"
  description = "AMI Generated by Packer"
}
